#!/bin/bash

CMD="$1"

if [[ "$CMD" == "build" ]]; then
  *TBW*
elif [[ "$CMD" == "clean" || "$CMD" == "sandbox" ]]; then
  docker exec -it poc-api bash -c "cd /opt/api && PYTHONPATH=. python scripts/manager.py '$CMD'"
elif [[ "$CMD" == "psql" ]]; then
  *TBW*
elif [[ "$CMD" == "python" ]]; then
  docker exec -it poc-api bash -c "cd /opt/api && PYTHONPATH=. python -i scripts/shell.py"
elif [[ "$CMD" == "rebuild" ]]; then
  *TBW*
elif [[ "$CMD" == "rmdb" ]]; then
	*TBW*
elif [[ "$CMD" == "restart" ]]; then
  *TBW*
elif [[ "$CMD" == "start" ]]; then
  docker-compose up
fi
